# Generated by Django 3.0.1 on 2020-02-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('dateofbirth', models.DateTimeField()),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('spk_lng', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='pic')),
                ('resume', models.ImageField(upload_to='resume')),
            ],
            options={
                'db_table': 'personal_data',
            },
        ),
    ]
