# Generated by Django 3.0.1 on 2020-02-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_data',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='personal_data',
            old_name='lname',
            new_name='lastname',
        ),
    ]
