# Generated by Django 3.0.1 on 2020-02-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200223_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
