# Generated by Django 3.0.1 on 2020-02-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200223_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_data',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
    ]
