# Generated by Django 3.0.1 on 2020-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200223_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('pass_year', models.DateField()),
                ('university', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=200)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='MyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_url', models.URLField()),
            ],
            options={
                'db_table': 'mylinks',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='project')),
                ('site_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('stars', models.FloatField()),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
