# Generated by Django 3.0.1 on 2020-02-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactus_education_experience_mylinks_projects_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_data',
            new_name='PersonalData',
        ),
    ]
