# Generated by Django 3.0.3 on 2020-02-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200301_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='latest_tech',
            field=models.TextField(default=None),
        ),
    ]
