# Generated by Django 3.0.3 on 2020-02-29 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200301_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='blog_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
