# Generated by Django 3.0.3 on 2020-03-01 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_personaldata_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
