# Generated by Django 3.0.3 on 2020-03-01 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_experience_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
